const dropdownProps = [
  {
    name: 'value',
    type: 'V | V[] | null',
    defaultValue: null,
    description: 'Current value of dropdown or value array if multiple',
  },
  {
    name: 'placeholder',
    type: 'string',
    defaultValue: "'Select'",
    description: 'Placeholder in input',
  },
  {
    name: 'options',
    type: 'Option<V, T>[]',
    defaultValue: null,
    description: 'Dropdown options',
  },
  {
    name: 'onChange',
    type: '(v: V | V[] | null) => void',
    defaultValue: null,
    description: 'Event handler for value change',
  },
  {
    name: 'onOpen',
    type: '() => void',
    defaultValue: null,
    description: 'OnOpen handler',
  },
  {
    name: 'onBlur',
    type: '(e: FocusEvent) => void',
    defaultValue: null,
    description: 'OnBlur handler',
  },
  {
    name: 'onFocus',
    type: '(e: FocusEvent) => void',
    defaultValue: null,
    description: 'OnFocus handler',
  },
  {
    name: 'onDelete',
    type: '(v: V) => void',
    defaultValue: null,
    description: 'Callback triggered on deletion',
  },
  {
    name: 'clearable',
    type: 'boolean',
    defaultValue: null,
    description: 'Can you clear the selection',
  },
  {
    name: 'closeOnEsc',
    type: 'boolean',
    defaultValue: 'true',
    description: 'Whether or not to close dropdown on ESC (escape)',
  },
  {
    name: 'disabled',
    type: 'boolean',
    defaultValue: null,
    description: 'Is the dropdown disabled',
  },
  {
    name: 'error',
    type: 'boolean',
    defaultValue: null,
    description: 'Did an error occur. Alert user when true',
  },
  {
    name: 'search',
    type: 'boolean | QueryMatchFn<V, T>',
    defaultValue: null,
    description: 'Are options currently loading?',
  },
  {
    name: 'renderOption',
    type: 'RenderOption<V, T>',
    defaultValue: null,
    description: 'Custom method for rendering option',
  },
  {
    name: 'noResultsMessage',
    type: 'React.ReactNode',
    defaultValue: "'No results'",
    description: 'Message to display when there are no results',
  },
  {
    name: 'className',
    type: 'string',
    defaultValue: null,
    description: 'Class names of outer wrapper',
  },
  {
    name: 'label',
    type: 'string',
    defaultValue: null,
    description: 'If the dropdown has a label',
  },
  {
    name: 'menuPosition',
    type: "'top' | 'bottom' | 'auto'",
    defaultValue: "'bottom'",
    description: 'Open dropdown position',
  },
  {
    name: 'minimal',
    type: 'boolean',
    defaultValue: null,
    description: 'Is this a minimal dropdown',
  },
  {
    name: 'selectedPrefix',
    type: 'string',
    defaultValue: null,
    description: 'Prefix of a selected item',
  },
  {
    name: 'style',
    type: 'React.CSSProperties',
    defaultValue: null,
    description: 'Adds a style to the component',
  },
] as const;

export default dropdownProps;
